apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-netk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cpee-tenant/status-quarkus-io/statusquarkusio-netk@sha256:eb1658c2c34f5d567fac61bd2fabf74eed597cc55b5064a3599fc102ed27894f
        name: my-java-quarkus
        resources: {}
status: {}
